namespace vm2.RegexLib.Tests;

public partial class NetTests
{
    public static TheoryData<string, bool, string, Captures?> Ipv4AddressData = new() {
        { TestFileLine(), false, "", null },
        { TestFileLine(), false, " ", null },
        { TestFileLine(), false, ".", null },
        { TestFileLine(), false, "a", null },
        { TestFileLine(), false, "abc", null },
        { TestFileLine(), false, "a.b.c", null },
        { TestFileLine(), false, "a.b.c.d", null },
        { TestFileLine(), false, "1", null },
        { TestFileLine(), false, "1.2", null },
        { TestFileLine(), false, "1.2.3", null },
        { TestFileLine(), false, "1.2.3.256", null },
        { TestFileLine(), false, "1.1.256.1", null },
        { TestFileLine(), false, "1.256.1.1", null },
        { TestFileLine(), false, "1000.1.1.1", null },
        { TestFileLine(), false, "1.1.1.1.1", null },
        { TestFileLine(), false, "1.1.1.1.", null },
        { TestFileLine(), false, " 1.1.1.1", null },
        { TestFileLine(), false, "1.1.1.1 ", null },
        { TestFileLine(), false, " 1.1.1.1 ", null },
        { TestFileLine(), false, "-1.1.1.1", null },
        { TestFileLine(), false, "0.1.1.1", null },
        { TestFileLine(), false, "01.1.1.1", null },
        { TestFileLine(), false, "01.01.01.01", null },
        { TestFileLine(), false, "256.256.256.256", null },
        { TestFileLine(), false, "0.0.0.0", null },
        { TestFileLine(), false, "0.0.0.1", null },
        { TestFileLine(), false, "0.255.255.255", null },
        { TestFileLine(), false, "255.255.255.255", null },
        { TestFileLine(), false, "240.0.0.0", null },
        { TestFileLine(), false, "240.1.2.3", null },
        { TestFileLine(), false, "240.255.255.255", null },
        { TestFileLine(), false, "192.0.2.0", null },
        { TestFileLine(), false, "192.0.2.255", null },
        { TestFileLine(), false, "198.51.100.0", null },
        { TestFileLine(), false, "198.51.100.255", null },
        { TestFileLine(), false, "203.0.113.0", null },
        { TestFileLine(), false, "203.0.113.255", null },
        { TestFileLine(), false, "192.0.2.128", null },
        { TestFileLine(), true,  "192.168.0.17", new() { ["ipv4"] = "192.168.0.17", } },
        { TestFileLine(), true,  "1.1.1.1",      new() { ["ipv4"] = "1.1.1.1",      } },
        { TestFileLine(), true,  "1.10.1.1",     new() { ["ipv4"] = "1.10.1.1",     } },
        { TestFileLine(), true,  "127.0.0.1",    new() { ["ipv4"] = "127.0.0.1",    } },
    };
}
