namespace vm2.RegexLibTests;

public partial class UrisTests
{
    public static UriTheoryData UriData = new () {
        { TestLine(), false, "", null },
        { TestLine(), false, " ", null },
        { TestLine(), false, "http://www.example.com/#hello, world", new() {
                ["uri"] = "http://www.example.com/#hello,%20world", // →uri← = →http://www.example.com/#hello, world←
                ["scheme"] = "http",
                ["authority"] = "www.example.com",
                ["address"] = "www.example.com",
                ["host"] = "www.example.com",
                ["ipDnsName"] = "www.example.com",
                ["pathAbsEmpty"] = "/",
                ["fragment"] = "hello,%20world", // →fragment← = →hello, world←
            } },
        { TestLine(), true, "http://www.example.com/#%c2%a9", new() {
                ["uri"] = "http://www.example.com/#%c2%a9", // →uri← = →http://www.example.com/#©←
                ["scheme"] = "http",
                ["authority"] = "www.example.com",
                ["address"] = "www.example.com",
                ["host"] = "www.example.com",
                ["ipDnsName"] = "www.example.com",
                ["pathAbsEmpty"] = "/",
                ["fragment"] = "%c2%a9", // →fragment← = →©←
            } },
        { TestLine(), false, "http://www.example.com/#\ud800\udf00ss", null },
        { TestLine(), false, "http://www.example.com/#%41%a", null },
        { TestLine(), false, "http://www.example.com/#\\ud800\\u597d", null },
        { TestLine(), false, "http://www.example.com/#a\\uFDD0", null },
        { TestLine(), false, "http://www.example.com/#asdf#qwer", null },
        { TestLine(), false, "http://www.example.com/##asdf", null },
        { TestLine(), false, "http://www.example.com/#a\u000Ab\u000Dc\u0009d", null },
        { TestLine(), false, "file:c:\\foo\\bar.html", null },
        { TestLine(), false, "File:c|////foo\\bar.html", null },
        { TestLine(), false, "  File:c|////foo\\bar.html", null },
        { TestLine(), false, "file:", null },
        { TestLine(), false, "file:UNChost/path", null },
        { TestLine(), false, "c:\\foo\\bar", null },
        { TestLine(), false, "C|/foo/bar", null },
        { TestLine(), false, "/C|\\foo\\bar", null },
        { TestLine(), false, "//C|/foo/bar", null },
        { TestLine(), false, "//server/file", null },
        { TestLine(), false, "\\\\server\\file", null },
        { TestLine(), false, "/\\server/file", null },
        { TestLine(), false, "file:c:foo/bar.html", null },
        { TestLine(), false, "file:/\\/\\C:\\\\//foo\\bar.html", null },
        { TestLine(), false, "file:///foo/bar.txt", null },
        { TestLine(), false, "FILE:/\\/\\7:\\\\//foo\\bar.html", null },
        { TestLine(), false, "file:filer/home\\me", null },
        { TestLine(), false, "file:///C:/foo/../../../bar.html", null },
        { TestLine(), false, "file:///C:/asdf#\\%c2", null },
        { TestLine(), false, "file:///home/me", null },
        { TestLine(), false, "file:c:\\foo\\bar.html", null },
        { TestLine(), false, "file:c|//foo\\bar.html", null },
        { TestLine(), false, "//", null },
        { TestLine(), false, "///", null },
        { TestLine(), false, "///test", null },
        { TestLine(), true, "file://test", new() {
                ["uri"] = "file://test",
                ["scheme"] = "file",
                ["authority"] = "test",
                ["address"] = "test",
                ["host"] = "test",
                ["ipDnsName"] = "test",
            } },
        { TestLine(), true, "file://localhost/", new() {
                ["uri"] = "file://localhost/",
                ["scheme"] = "file",
                ["authority"] = "localhost",
                ["address"] = "localhost",
                ["host"] = "localhost",
                ["ipDnsName"] = "localhost",
                ["pathAbsEmpty"] = "/",
            } },
        { TestLine(), true, "file://localhost/test", new() {
                ["uri"] = "file://localhost/test",
                ["scheme"] = "file",
                ["authority"] = "localhost",
                ["address"] = "localhost",
                ["host"] = "localhost",
                ["ipDnsName"] = "localhost",
                ["pathAbsEmpty"] = "/test",
            } },
        { TestLine(), false, "file:c:\\foo\\bar.html", null },
        { TestLine(), false, "  File:c|////foo\\bar.html", null },
        { TestLine(), false, "file:", null },
        { TestLine(), false, "file:UNChost/path", null },
        { TestLine(), false, "c:\\foo\\bar", null },
        { TestLine(), false, "C|/foo/bar", null },
        { TestLine(), false, "/C|\\foo\\bar", null },
        { TestLine(), false, "//C|/foo/bar", null },
        { TestLine(), false, "//server/file", null },
        { TestLine(), false, "\\\\server\\file", null },
        { TestLine(), false, "/\\server/file", null },
        { TestLine(), false, "file:c:foo/bar.html", null },
        { TestLine(), false, "file:/\\/\\C:\\\\//foo\\bar.html", null },
        { TestLine(), false, "file:///foo/bar.txt", null },
        { TestLine(), false, "FILE:/\\/\\7:\\\\//foo\\bar.html", null },
        { TestLine(), false, "file:filer/home\\me", null },
        { TestLine(), false, "file:///C:/foo/../../../bar.html", null },
        { TestLine(), false, "file:///C:/asdf#\\%c2", null },
        { TestLine(), false, "file:///home/me", null },
        { TestLine(), false, "file:c:\\foo\\bar.html", null },
        { TestLine(), false, "file:c|//foo\\bar.html", null },
        { TestLine(), false, "//", null },
        { TestLine(), false, "///", null },
        { TestLine(), false, "///test", null },
        { TestLine(), true, "file://test", new() {
                ["uri"] = "file://test",
                ["scheme"] = "file",
                ["authority"] = "test",
                ["address"] = "test",
                ["host"] = "test",
                ["ipDnsName"] = "test",
            } },
        { TestLine(), true, "file://localhost/", new() {
                ["uri"] = "file://localhost/",
                ["scheme"] = "file",
                ["authority"] = "localhost",
                ["address"] = "localhost",
                ["host"] = "localhost",
                ["ipDnsName"] = "localhost",
                ["pathAbsEmpty"] = "/",
            } },
        { TestLine(), true, "file://localhost/test", new() {
                ["uri"] = "file://localhost/test",
                ["scheme"] = "file",
                ["authority"] = "localhost",
                ["address"] = "localhost",
                ["host"] = "localhost",
                ["ipDnsName"] = "localhost",
                ["pathAbsEmpty"] = "/test",
            } },
        { TestLine(), true, "http://GoOgLe.CoM", new() {
                ["uri"] = "http://GoOgLe.CoM",
                ["scheme"] = "http",
                ["authority"] = "GoOgLe.CoM",
                ["address"] = "GoOgLe.CoM",
                ["host"] = "GoOgLe.CoM",
                ["ipDnsName"] = "GoOgLe.CoM",
            } },
        { TestLine(), false, "http://Goo%20 goo%7C|.com", null },
        { TestLine(), false, "http://GOO\u00a0\u3000goo.com", null },
        { TestLine(), false, "http://GOO\u200b\u2060\ufeffgoo.com", null },
        { TestLine(), false, "http://www.foo\u3002bar.com", null },
        { TestLine(), false, "http://\ufdd0zyx.com", null },
        { TestLine(), true,  "http://%ef%b7%90zyx.com", new() {
                ["uri"] = "http://%ef%b7%90zyx.com", // →uri← = →http://﷐zyx.com←
                ["scheme"] = "http",
                ["authority"] = "%ef%b7%90zyx.com", // →authority← = →﷐zyx.com←
                ["address"] = "%ef%b7%90zyx.com", // →address← = →﷐zyx.com←
                ["host"] = "%ef%b7%90zyx.com", // →host← = →﷐zyx.com←
                ["ipGenName"] = "%ef%b7%90zyx.com", // →ipGenName← = →﷐zyx.com←
            } },
        { TestLine(), false, "http://\uff27\uff4f.com", null },
        { TestLine(), false, "http://\uff05\uff14\uff11.com", null },
        { TestLine(), true,  "http://%ef%bc%85%ef%bc%94%ef%bc%91.com", new() {
                ["uri"] = "http://%ef%bc%85%ef%bc%94%ef%bc%91.com", // →uri← = →http://％４１.com←
                ["scheme"] = "http",
                ["authority"] = "%ef%bc%85%ef%bc%94%ef%bc%91.com", // →authority← = →％４１.com←
                ["address"] = "%ef%bc%85%ef%bc%94%ef%bc%91.com", // →address← = →％４１.com←
                ["host"] = "%ef%bc%85%ef%bc%94%ef%bc%91.com", // →host← = →％４１.com←
                ["ipGenName"] = "%ef%bc%85%ef%bc%94%ef%bc%91.com", // →ipGenName← = →％４１.com←
            } },
        { TestLine(), false, "http://\uff05\uff10\uff10.com", null },
        { TestLine(), true,  "http://%ef%bc%85%ef%bc%90%ef%bc%90.com", new() {
                ["uri"] = "http://%ef%bc%85%ef%bc%90%ef%bc%90.com", // →uri← = →http://％００.com←
                ["scheme"] = "http",
                ["authority"] = "%ef%bc%85%ef%bc%90%ef%bc%90.com", // →authority← = →％００.com←
                ["address"] = "%ef%bc%85%ef%bc%90%ef%bc%90.com", // →address← = →％００.com←
                ["host"] = "%ef%bc%85%ef%bc%90%ef%bc%90.com", // →host← = →％００.com←
                ["ipGenName"] = "%ef%bc%85%ef%bc%90%ef%bc%90.com", // →ipGenName← = →％００.com←
            } },
        { TestLine(), false, "http://\u4f60\u597d\u4f60\u597d", null },
        { TestLine(), false, "http://%E4%BD%A0%E5%A5%BD\u4f60\u597d", null },
        { TestLine(), false, "http://%zz%66%a", null },
        { TestLine(), true,  "http://%25", new() {
                ["uri"] = "http://%25", // →uri← = →http://%←
                ["scheme"] = "http",
                ["authority"] = "%25", // →authority← = →%←
                ["address"] = "%25", // →address← = →%←
                ["host"] = "%25", // →host← = →%←
                ["ipGenName"] = "%25", // →ipGenName← = →%←
            } },
        { TestLine(), true,  "http://hello%00", new() {
                ["uri"] = "http://hello%00", // →uri← = →http://hello ←
                ["scheme"] = "http",
                ["authority"] = "hello%00", // →authority← = →hello ←
                ["address"] = "hello%00", // →address← = →hello ←
                ["host"] = "hello%00", // →host← = →hello ←
                ["ipGenName"] = "hello%00", // →ipGenName← = →hello ←
            } },
        { TestLine(), true,  "http://%30%78%63%30%2e%30%32%35%30.01", new() {
                ["uri"] = "http://%30%78%63%30%2e%30%32%35%30.01", // →uri← = →http://0xc0.0250.01←
                ["scheme"] = "http",
                ["authority"] = "%30%78%63%30%2e%30%32%35%30.01", // →authority← = →0xc0.0250.01←
                ["address"] = "%30%78%63%30%2e%30%32%35%30.01", // →address← = →0xc0.0250.01←
                ["host"] = "%30%78%63%30%2e%30%32%35%30.01", // →host← = →0xc0.0250.01←
                ["ipGenName"] = "%30%78%63%30%2e%30%32%35%30.01", // →ipGenName← = →0xc0.0250.01←
            } },
        { TestLine(), true,  "http://%30%78%63%30%2e%30%32%35%30.01%2e", new() {
                ["uri"] = "http://%30%78%63%30%2e%30%32%35%30.01%2e", // →uri← = →http://0xc0.0250.01.←
                ["scheme"] = "http",
                ["authority"] = "%30%78%63%30%2e%30%32%35%30.01%2e", // →authority← = →0xc0.0250.01.←
                ["address"] = "%30%78%63%30%2e%30%32%35%30.01%2e", // →address← = →0xc0.0250.01.←
                ["host"] = "%30%78%63%30%2e%30%32%35%30.01%2e", // →host← = →0xc0.0250.01.←
                ["ipGenName"] = "%30%78%63%30%2e%30%32%35%30.01%2e", // →ipGenName← = →0xc0.0250.01.←
            } },
        { TestLine(), false, "http://%3g%78%63%30%2e%30%32%35%30%2E.01", null },
        { TestLine(), false, "http://192.168.0.1 hello", null },
        { TestLine(), false, "http://\uff10\uff38\uff43\uff10\uff0e\uff10\uff12\uff15\uff10\uff0e\uff10\uff11", null },
        { TestLine(), true,  "http://192.168.0.257", new() {
                ["uri"] = "http://192.168.0.257",
                ["scheme"] = "http",
                ["authority"] = "192.168.0.257",
                ["address"] = "192.168.0.257",
                ["host"] = "192.168.0.257",
                ["ipGenName"] = "192.168.0.257",
            } },
        { TestLine(), false, "http://[google.com]", null },
        { TestLine(), false, "http://\u0442(", null },
        { TestLine(), false, "http://go\\@ogle.com", null },
        { TestLine(), true,  "http://go/@ogle.com", new() {
                ["uri"] = "http://go/@ogle.com",
                ["scheme"] = "http",
                ["authority"] = "go",
                ["address"] = "go",
                ["host"] = "go",
                ["ipDnsName"] = "go",
                ["pathAbsEmpty"] = "/@ogle.com",
            } },
        { TestLine(), true,  "http://www.lookout.net::==80::==443::", new() {
                ["uri"] = "http://www.lookout.net::==80::==443::",
                ["scheme"] = "http",
                ["pathAbs"] = "/www.lookout.net::==80::==443::",
            } },
        { TestLine(), true,  "http://www.lookout.net::80::443", new() {
                ["uri"] = "http://www.lookout.net::80::443",
                ["scheme"] = "http",
                ["pathAbs"] = "/www.lookout.net::80::443",
            } },
        { TestLine(), false, "http://\\", null },
        { TestLine(), false, "http://\\/", null },
        { TestLine(), false, "http://\\./", null },
        { TestLine(), false, "http:////:@/", null },
        { TestLine(), false, "http://\\google.com/foo", null },
        { TestLine(), false, "http://\\google.com/foo", null },
        { TestLine(), false, "http:////asdf@/", null },
        { TestLine(), false, "http:////:81", null },
        { TestLine(), true,  "http://://", new() {
                ["uri"] = "http://://",
                ["scheme"] = "http",
                ["pathAbs"] = "/://",
            } },
        { TestLine(), true,  "http://c:", new() {
                ["uri"] = "http://c:",
                ["scheme"] = "http",
                ["pathAbs"] = "/c:",
            } },
        { TestLine(), true,  "http://xxxx:", new() {
                ["uri"] = "http://xxxx:",
                ["scheme"] = "http",
                ["pathAbs"] = "/xxxx:",
            } },
        { TestLine(), true,  "http://.:.", new() {
                ["uri"] = "http://.:.",
                ["scheme"] = "http",
                ["pathAbs"] = "/.:.",
            } },
        { TestLine(), false, "http://////@google.com/", null },
        { TestLine(), true,  "http://@google.com", new() {
            ["uri"] = "http://@google.com",
            ["scheme"] = "http",
            ["pathAbs"] = "/@google.com",
        } },
        { TestLine(), false, "http://fa\u00DF.de", null },
        { TestLine(), false, "http://\u03B2\u03CC\u03BB\u03BF\u03C2.com", null },
        { TestLine(), false, "http://\u0DC1\u0DCA\u200D\u0DBB\u0DD3.com", null },
        { TestLine(), false, "http://\u0646\u0627\u0645\u0647\u200C\u0627\u06CC.com", null },
        { TestLine(), false, "http://www.loo\u0138out.net", null },
        { TestLine(), false, "http://\u15EF\u15EF\u15EF.lookout.net", null },
        { TestLine(), false, "http://www.lookout.\u0441\u043E\u043C", null },
        { TestLine(), false, "http://www.lookout.net\uFF1A80", null },
        { TestLine(), false, "http://www\u2025lookout.net", null },
        { TestLine(), false, "http://www.lookout\u2027net", null },
        { TestLine(), false, "http://www.loo\u0138out.net", null },
        { TestLine(), false, "http://www.lookout.net\u2A7480", null },
        { TestLine(), false, "http://www\u00A0.lookout.net", null },
        { TestLine(), false, "http://\u1680lookout.net", null },
        { TestLine(), false, "http://\u001Flookout.net", null },
        { TestLine(), false, "http://look\u06DDout.net", null },
        { TestLine(), false, "http://look\u180Eout.net", null },
        { TestLine(), false, "http://look\u2060out.net", null },
        { TestLine(), false, "http://look\uFEFFout.net", null },
        { TestLine(), false, "http://look\uD83F\uDFFEout.net", null },
        { TestLine(), false, "http://look\uDEADout.net", null },
        { TestLine(), false, "http://look\uFFFAout.net", null },
        { TestLine(), false, "http://look\u2FF0out.net", null },
        { TestLine(), false, "http://look\u0341out.net", null },
        { TestLine(), false, "http://look\u202Eout.net", null },
        { TestLine(), false, "http://look\u206Bout.net", null },
        { TestLine(), false, "http://look\uDB40\uDC01out.net", null },
        { TestLine(), false, "http://look\uDB40\uDC20out.net", null },
        { TestLine(), false, "http://look\u05BEout.net", null },
        { TestLine(), false, "http://B\u00FCcher.de", null },
        { TestLine(), false, "http://fa\u00DF.de", null },
        { TestLine(), false, "http://\u03B2\u03CC\u03BB\u03BF\u03C2.com", null },
        { TestLine(), false, "http://\u0DC1\u0DCA\u200D\u0DBB\u0DD3.com", null },
        { TestLine(), false, "http://\u0646\u0627\u0645\u0647\u200C\u0627\u06CC.com", null },
        { TestLine(), false, "http://\u2665.net", null },
        { TestLine(), false, "http://\u0378.net", null },
        { TestLine(), false, "http://\u04C0.com", null },
        { TestLine(), false, "http://\uD87E\uDC68.com", null },
        { TestLine(), false, "http://\u2183.com", null },
        { TestLine(), false, "http://look\u034Fout.net", null },
        { TestLine(), true,  "http://gOoGle.com", new() {
                ["uri"] = "http://gOoGle.com",
                ["scheme"] = "http",
                ["authority"] = "gOoGle.com",
                ["address"] = "gOoGle.com",
                ["host"] = "gOoGle.com",
                ["ipDnsName"] = "gOoGle.com",
            } },
        { TestLine(), false, "http://\u09dc.com", null },
        { TestLine(), false, "http://\u1E9E.com", null },
        { TestLine(), false, "http://\u1E9E.foo.com", null },
        { TestLine(), true,  "http://-foo.bar.com", new() {
                ["uri"] = "http://-foo.bar.com",
                ["scheme"] = "http",
                ["authority"] = "-foo.bar.com",
                ["address"] = "-foo.bar.com",
                ["host"] = "-foo.bar.com",
                ["ipGenName"] = "-foo.bar.com",
            } },
        { TestLine(), true,  "http://foo-.bar.com", new() {
            ["uri"] = "http://foo-.bar.com",
            ["scheme"] = "http",
            ["authority"] = "foo-.bar.com",
            ["address"] = "foo-.bar.com",
            ["host"] = "foo-.bar.com",
            ["ipGenName"] = "foo-.bar.com",
        } },
        //{ TestLine(), false, "http://ab--cd.com", null },
        //{ TestLine(), false, "http://xn--0.com", null },
        //{ TestLine(), false, "http://foo\u0300.bar.com", null },
        //{ TestLine(), false, "http://.", null },
        //{ TestLine(), false, "http://192.168.0.1", null },
        //{ TestLine(), false, "http://0300.0250.00.01", null },
        //{ TestLine(), false, "http://0xC0.0Xa8.0x0.0x1", null },
        //{ TestLine(), false, "http://192.168.9.com", null },
        //{ TestLine(), false, "http://19a.168.0.1", null },
        //{ TestLine(), false, "http://0308.0250.00.01", null },
        //{ TestLine(), false, "http://0xCG.0xA8.0x0.0x1", null },
        //{ TestLine(), false, "http://192", null },
        //{ TestLine(), false, "http://0xC0a80001", null },
        //{ TestLine(), false, "http://030052000001", null },
        //{ TestLine(), false, "http://000030052000001", null },
        //{ TestLine(), false, "http://192.168", null },
        //{ TestLine(), false, "http://192.0x00A80001", null },
        //{ TestLine(), false, "http://0xc0.052000001", null },
        //{ TestLine(), false, "http://192.168.1", null },
        //{ TestLine(), false, "http://192.168.0.0.1", null },
        //{ TestLine(), false, "http://192.168.0.1.", null },
        //{ TestLine(), false, "http://192.168.0.1. hello", null },
        //{ TestLine(), false, "http://192.168.0.1..", null },
        //{ TestLine(), false, "http://192.168..1", null },
        //{ TestLine(), false, "http://0x100.0", null },
        //{ TestLine(), false, "http://0x100.0.0", null },
        //{ TestLine(), false, "http://0x100.0.0.0", null },
        //{ TestLine(), false, "http://0.0x100.0.0", null },
        //{ TestLine(), false, "http://0.0.0x100.0", null },
        //{ TestLine(), false, "http://0.0.0.0x100", null },
        //{ TestLine(), false, "http://0.0.0x10000", null },
        //{ TestLine(), false, "http://0.0x1000000", null },
        //{ TestLine(), false, "http://0x100000000", null },
        //{ TestLine(), false, "http://0xFF.0", null },
        //{ TestLine(), false, "http://0xFF.0.0", null },
        //{ TestLine(), false, "http://0xFF.0.0.0", null },
        //{ TestLine(), false, "http://0.0xFF.0.0", null },
        //{ TestLine(), false, "http://0.0.0xFF.0", null },
        //{ TestLine(), false, "http://0.0.0.0xFF", null },
        //{ TestLine(), false, "http://0.0.0xFFFF", null },
        //{ TestLine(), false, "http://0.0xFFFFFF", null },
        //{ TestLine(), false, "http://0xFFFFFFFF", null },
        //{ TestLine(), false, "http://276.256.0xf1a2.077777", null },
        //{ TestLine(), false, "http://192.168.0.257", null },
        //{ TestLine(), false, "http://192.168.0xa20001", null },
        //{ TestLine(), false, "http://192.015052000001", null },
        //{ TestLine(), false, "http://0X12C0a80001", null },
        //{ TestLine(), false, "http://276.1.2", null },
        //{ TestLine(), false, "http://192.168.0.1 hello", null },
        //{ TestLine(), false, "http://0000000000000300.0x00000000000000fF.00000000000000001", null },
        //{ TestLine(), false, "http://0000000000000300.0xffffffffFFFFFFFF.3022415481470977", null },
        //{ TestLine(), false, "http://00000000000000000001", null },
        //{ TestLine(), false, "http://0000000000000000100000000000000001", null },
        //{ TestLine(), false, "http://0.0.0.000000000000000000z", null },
        //{ TestLine(), false, "http://0.0.0.100000000000000000z", null },
        //{ TestLine(), false, "http://0.00.0x.0x0", null },
        //{ TestLine(), false, "http://[", null },
        //{ TestLine(), false, "http://[:", null },
        //{ TestLine(), false, "http://]", null },
        //{ TestLine(), false, "http://:]", null },
        //{ TestLine(), false, "http://[]", null },
        //{ TestLine(), false, "http://[:]", null },
        //{ TestLine(), false, "http://2001:db8::1", null },
        //{ TestLine(), false, "http://[2001:db8::1", null },
        //{ TestLine(), false, "http://2001:db8::1]", null },
        //{ TestLine(), false, "http://[::]", null },
        //{ TestLine(), false, "http://[::1]", null },
        //{ TestLine(), false, "http://[1::]", null },
        //{ TestLine(), false, "http://[::192.168.0.1]", null },
        //{ TestLine(), false, "http://[::ffff:192.168.0.1]", null },
        //{ TestLine(), false, "http://[000:01:02:003:004:5:6:007]", null },
        //{ TestLine(), false, "http://[A:b:c:DE:fF:0:1:aC]", null },
        //{ TestLine(), false, "http://[1:0:0:2::3:0]", null },
        //{ TestLine(), false, "http://[1::2:0:0:3:0]", null },
        //{ TestLine(), false, "http://[::eeee:192.168.0.1]", null },
        //{ TestLine(), false, "http://[2001::192.168.0.1]", null },
        //{ TestLine(), false, "http://[1:2:192.168.0.1:5:6]", null },
        //{ TestLine(), false, "http://[::ffff:192.1.2]", null },
        //{ TestLine(), false, "http://[::ffff:0xC0.0Xa8.0x0.0x1]", null },
        //{ TestLine(), false, "http://[0:0::0:0:8]", null },
        //{ TestLine(), false, "http://[2001:db8::1]", null },
        //{ TestLine(), false, "http://[2001::db8::1]", null },
        //{ TestLine(), false, "http://[2001:db8:::1]", null },
        //{ TestLine(), false, "http://[:::]", null },
        //{ TestLine(), false, "http://[2001::.com]", null },
        //{ TestLine(), false, "http://[::192.168.0.0.1]", null },
        //{ TestLine(), false, "http://[::ffff:192.168.0.0.1]", null },
        //{ TestLine(), false, "http://[1:2:3:4:5:6:7:8:9]", null },
        //{ TestLine(), false, "http://[0:0:0:0:0:0:0:192.168.0.1]", null },
        //{ TestLine(), false, "http://[1:2:3:4:5:6::192.168.0.1]", null },
        //{ TestLine(), false, "http://[1:2:3:4:5:6::8]", null },
        //{ TestLine(), false, "http://[1:2:3:4:5:6:7:8:]", null },
        //{ TestLine(), false, "http://[1:2:3:4:5:6:192.168.0.1:]", null },
        //{ TestLine(), false, "http://[-1:2:3:4:5:6:7:8]", null },
        //{ TestLine(), false, "http://[1::%1]", null },
        //{ TestLine(), false, "http://[1::%eth0]", null },
        //{ TestLine(), false, "http://[1::%]", null },
        //{ TestLine(), false, "http://[%]", null },
        //{ TestLine(), false, "http://[::%:]", null },
        //{ TestLine(), false, "http://[:0:0::0:0:8]", null },
        //{ TestLine(), false, "http://[0:0::0:0:8:]", null },
        //{ TestLine(), false, "http://[:0:0::0:0:8:]", null },
        //{ TestLine(), false, "http://[::192.168..1]", null },
        //{ TestLine(), false, "http://[::1 hello]", null },
        //{ TestLine(), false, "mailto:addr1", null },
        //{ TestLine(), false, "mailto:addr1@foo.com", null },
        //{ TestLine(), false, "mailto:addr1 \t", null },
        //{ TestLine(), false, "mailto:addr1?to=jon", null },
        //{ TestLine(), false, "mailto:addr1,addr2", null },
        //{ TestLine(), false, "mailto:addr1, addr2", null },
        //{ TestLine(), false, "mailto:addr1%2caddr2", null },
        //{ TestLine(), false, "mailto:\uD800\uDF00", null },
        //{ TestLine(), false, "mailto:addr1?", null },
        //{ TestLine(), false, "javascript:", null },
        //{ TestLine(), false, "JavaScript:Foo", null },
        //{ TestLine(), false, "http://www.example.com/././foo", null },
        //{ TestLine(), false, "http://www.example.com/./.foo", null },
        //{ TestLine(), false, "http://www.example.com/foo/.", null },
        //{ TestLine(), false, "http://www.example.com/foo/./", null },
        //{ TestLine(), false, "http://www.example.com/foo/bar/..", null },
        //{ TestLine(), false, "http://www.example.com/foo/bar/../", null },
        //{ TestLine(), false, "http://www.example.com/foo/..bar", null },
        //{ TestLine(), false, "http://www.example.com/foo/bar/../ton", null },
        //{ TestLine(), false, "http://www.example.com/foo/bar/../ton/../../a", null },
        //{ TestLine(), false, "http://www.example.com/foo/../../..", null },
        //{ TestLine(), false, "http://www.example.com/foo/../../../ton", null },
        //{ TestLine(), false, "http://www.example.com/foo/%2e", null },
        //{ TestLine(), false, "http://www.example.com/foo/%2e%2", null },
        //{ TestLine(), false, "http://www.example.com/foo/%2e./%2e%2e/.%2e/%2e.bar", null },
        //{ TestLine(), false, "http://www.example.com////../..", null },
        //{ TestLine(), false, "http://www.example.com/foo/bar//../..", null },
        //{ TestLine(), false, "http://www.example.com/foo/bar//..", null },
        //{ TestLine(), false, "http://www.example.com/foo/bar/..", null },
        //{ TestLine(), false, "http://www.example.com/foo", null },
        //{ TestLine(), false, "http://www.example.com/%20foo", null },
        //{ TestLine(), false, "http://www.example.com/foo%", null },
        //{ TestLine(), false, "http://www.example.com/foo%2", null },
        //{ TestLine(), false, "http://www.example.com/foo%2zbar", null },
        //{ TestLine(), false, "http://www.example.com/foo%2\u00c2\u00a9zbar", null },
        //{ TestLine(), false, "http://www.example.com/foo%41%7a", null },
        //{ TestLine(), false, "http://www.example.com/foo\u0009\u0091%91", null },
        //{ TestLine(), false, "http://www.example.com/foo%00%51", null },
        //{ TestLine(), false, "http://www.example.com/(%28:%3A%29)", null },
        //{ TestLine(), false, "http://www.example.com/%3A%3a%3C%3c", null },
        //{ TestLine(), false, "http://www.example.com/foo\tbar", null },
        //{ TestLine(), false, "http://www.example.com\\foo\\bar", null },
        //{ TestLine(), false, "http://www.example.com/%7Ffp3%3Eju%3Dduvgw%3Dd", null },
        //{ TestLine(), false, "http://www.example.com/@asdf%40", null },
        //{ TestLine(), false, "http://www.example.com/\u4f60\u597d\u4f60\u597d", null },
        //{ TestLine(), false, "http://www.example.com/\ufdd0zyx", null },
        //{ TestLine(), false, "http://www.example.com/\u2025/foo", null },
        //{ TestLine(), false, "http://www.example.com/\uDEAD/foo", null },
        //{ TestLine(), false, "http://www.example.com/\uFEFF/foo", null },
        //{ TestLine(), false, "http://www.example.com/\u202E/foo/\u202D/bar", null },
        //{ TestLine(), false, "http://www.example.com\uFF0Ffoo/", null },
        //{ TestLine(), false, "http://www.example.com:as df", null },
        //{ TestLine(), false, "http://www.example.com:-2", null },
        //{ TestLine(), false, "http://www.example.com:80", null },
        //{ TestLine(), false, "http://www.example.com:8080", null },
        //{ TestLine(), false, "http://www.example.com:", null },
        //{ TestLine(), false, "http://www.example.com:\u1369", null },
        //{ TestLine(), false, "http://www.example.com:\uD835\uDFD6", null },
        //{ TestLine(), false, "http://www.example.com/?foo=bar", null },
        //{ TestLine(), false, "http://www.example.com/?as?df", null },
        //{ TestLine(), false, "http://www.example.com/?\%02hello%7f bye", null },
        //{ TestLine(), false, "http://www.example.com/?%40%41123", null },
        //{ TestLine(), false, "http://www.example.com/?q=\u4F60\u597D", null },
        //{ TestLine(), false, "http://www.example.com/?q=\\ud800\\ud800", null },
        //{ TestLine(), false, "http://www.example.com/?q=&lt;asdf&gt;", null },
        //{ TestLine(), false, "http://www.example.com/?q=""asdf""", null },
        //{ TestLine(), false, "\\\\Another\\path", null },
        //{ TestLine(), false, "/c:\\foo", null },
        //{ TestLine(), false, "//c:\\foo", null },
        //{ TestLine(), false, "http://host/", null },
        //{ TestLine(), false, "bar", null },
        //{ TestLine(), false, "../../../bar.html", null },
        //{ TestLine(), false, "/../bar.html", null },
        //{ TestLine(), false, "\\\\another\\path", null },
        //{ TestLine(), false, "//c:/foo", null },
        //{ TestLine(), false, "//localhost/c:/foo", null },
        //{ TestLine(), false, "c:", null },
        //{ TestLine(), false, "c:/foo", null },
        //{ TestLine(), false, "c:\\foo", null },
        //{ TestLine(), false, "/z:/bar", null },
        //{ TestLine(), false, "/bar", null },
        //{ TestLine(), false, "/bar", null },
        //{ TestLine(), false, "/bar", null },
        //{ TestLine(), false, "//somehost/path", null },
        //{ TestLine(), false, "/\\//somehost/path", null },
        //{ TestLine(), false, "http://another/", null },
        //{ TestLine(), false, "http:////another/", null },
        //{ TestLine(), false, "", null },
        //{ TestLine(), false, "", null },
        //{ TestLine(), false, "", null },
        //{ TestLine(), false, "  another", null },
        //{ TestLine(), false, "  .", null },
        //{ TestLine(), false, " \t", null },
        //{ TestLine(), false, "http:path", null },
        //{ TestLine(), false, "http:path", null },
        //{ TestLine(), false, "http:/path", null },
        //{ TestLine(), false, "HTTP:/path", null },
        //{ TestLine(), false, "https:host2", null },
        //{ TestLine(), false, "htto:/host2", null },
        //{ TestLine(), false, "/b/c/d", null },
        //{ TestLine(), false, "\\b\\c\\d", null },
        //{ TestLine(), false, "/b/../c", null },
        //{ TestLine(), false, "/b/../c", null },
        //{ TestLine(), false, "\\b/../c?x#y", null },
        //{ TestLine(), false, "/b/../c?x#y", null },
        //{ TestLine(), false, "b", null },
        //{ TestLine(), false, "bc/de", null },
        //{ TestLine(), false, "bc/de?query#ref", null },
        //{ TestLine(), false, ".", null },
        //{ TestLine(), false, "..", null },
        //{ TestLine(), false, "./..", null },
        //{ TestLine(), false, "../.", null },
        //{ TestLine(), false, "././.", null },
        //{ TestLine(), false, "../../../foo", null },
        //{ TestLine(), false, "?foo=bar", null },
        //{ TestLine(), false, "?", null },
        //{ TestLine(), false, "?foo=bar#com", null },
        //{ TestLine(), false, "#ref", null },
        //{ TestLine(), false, "#", null },
        //{ TestLine(), false, "#bye", null },
        //{ TestLine(), false, "baz.html", null },
        //{ TestLine(), false, "data:baz", null },
        //{ TestLine(), false, "data:/base", null },
        //{ TestLine(), false, "http://host/", null },
        //{ TestLine(), false, "http:host", null },
        //{ TestLine(), false, "./asd:fgh", null },
        //{ TestLine(), false, ":foo", null },
        //{ TestLine(), false, " hello world", null },
        //{ TestLine(), false, ":foo", null },
        //{ TestLine(), false, "; foo", null },
        //{ TestLine(), false, ";foo", null },
        //{ TestLine(), false, ";/../bar", null },
        //{ TestLine(), false, "//another", null },
        //{ TestLine(), false, "//another/path?query#ref", null },
        //{ TestLine(), false, "///another/path", null },
        //{ TestLine(), false, "//Another\\path", null },
        //{ TestLine(), false, "//", null },
        //{ TestLine(), false, "\\/another/path", null },
        //{ TestLine(), false, "/\\Another\\path", null },
        //{ TestLine(), false, "http://iris.test.ing", null },
        //{ TestLine(), false, "HTTP://iris.test.ing", null },
        //{ TestLine(), false, "http://user:pass@foo:21/bar;par?b#c", null },
        //{ TestLine(), false, "http:foo.com", null },
        //{ TestLine(), false, "\u0009   :foo.com   \u000A", null },
        //{ TestLine(), false, " foo.com", null },
        //{ TestLine(), false, "a:\u0009 foo.com", null },
        //{ TestLine(), false, "http://f:21/ b ? d # e ", null },
        //{ TestLine(), false, "http://f:/c", null },
        //{ TestLine(), false, "http://f:0/c", null },
        //{ TestLine(), false, "http://f:00000000000000/c", null },
        //{ TestLine(), false, "http://f:00000000000000000000080/c", null },
        //{ TestLine(), false, "http://f:b/c", null },
        //{ TestLine(), false, "http://f: /c", null },
        //{ TestLine(), false, "http://f:\u000A/c", null },
        //{ TestLine(), false, "http://f:fifty-two/c", null },
        //{ TestLine(), false, "http://f:999999/c", null },
        //{ TestLine(), false, "http://f: 21 / b ? d # e ", null },
        //{ TestLine(), false, "", null },
        //{ TestLine(), false, "  \u0009", null },
        //{ TestLine(), false, ":foo.com/", null },
        //{ TestLine(), false, ":foo.com\\", null },
        //{ TestLine(), false, ":", null },
        //{ TestLine(), false, ":a", null },
        //{ TestLine(), false, ":/", null },
        //{ TestLine(), false, ":\\", null },
        //{ TestLine(), false, ":#", null },
        //{ TestLine(), false, "#", null },
        //{ TestLine(), false, "#/", null },
        //{ TestLine(), false, "#\\", null },
        //{ TestLine(), false, "#;?", null },
        //{ TestLine(), false, "?", null },
        //{ TestLine(), false, "/", null },
        //{ TestLine(), false, ":23", null },
        //{ TestLine(), false, "/:23", null },
        //{ TestLine(), false, "//", null },
        //{ TestLine(), false, "::", null },
        //{ TestLine(), false, "::23", null },
        //{ TestLine(), false, "foo://", null },
        //{ TestLine(), false, "http://a:b@c:29/d", null },
        //{ TestLine(), false, "http::@c:29", null },
        //{ TestLine(), false, "http://&amp;a:foo(b]c@d:2/", null },
        //{ TestLine(), false, "http://::@c@d:2", null },
        //{ TestLine(), false, "http://foo.com:b@d/", null },
        //{ TestLine(), false, "http://foo.com/\\", null },
        //{ TestLine(), false, "http:\\\\foo.com\\", null },
        //{ TestLine(), false, "http:\\\\a\\b:c\\d @foo.com\\", null },
        //{ TestLine(), false, "foo:/", null },
        //{ TestLine(), false, "foo:/bar.com/", null },
        //{ TestLine(), false, "foo://///////", null },
        //{ TestLine(), false, "foo://///////bar.com/", null },
        //{ TestLine(), false, "foo:////://///", null },
        //{ TestLine(), false, "c:/foo", null },
        //{ TestLine(), false, "    //foo/bar", null },
        //{ TestLine(), false, "http://foo/path;a??e#f#g", null },
        //{ TestLine(), false, "http://foo/abcd?efgh?ijkl", null },
        //{ TestLine(), false, "http://foo/abcd#foo?bar", null },
        //{ TestLine(), false, "[61:24:74]:98", null },
        //{ TestLine(), false, "http://[61:27]:98", null },
        //{ TestLine(), false, "http:[61:27]/:foo", null },
        //{ TestLine(), false, "http://[1::2]:3:4", null },
        //{ TestLine(), false, "http://2001::1", null },
        //{ TestLine(), false, "http://[2001::1", null },
        //{ TestLine(), false, "http://2001::1]", null },
        //{ TestLine(), false, "http://2001::1]:80", null },
        //{ TestLine(), false, "http://[2001::1]", null },
        //{ TestLine(), false, "http://[2001::1]:80", null },
        //{ TestLine(), false, "http://[[::]]", null },
        //{ TestLine(), false, "http://user:pass@foo:21/bar;par?b#c", null },
        //{ TestLine(), false, "http:foo.com", null },
        //{ TestLine(), false, "\u0009   :foo.com   \u000A", null },
        //{ TestLine(), false, " foo.com", null },
        //{ TestLine(), false, "a:\u0009 foo.com", null },
        //{ TestLine(), false, "http://f:21/ b ? d # e ", null },
        //{ TestLine(), false, "http://f:/c", null },
        //{ TestLine(), false, "http://f:0/c", null },
        //{ TestLine(), false, "http://f:00000000000000/c", null },
        //{ TestLine(), false, "http://f:00000000000000000000080/c", null },
        //{ TestLine(), false, "http://f:b/c", null },
        //{ TestLine(), false, "http://f: /c", null },
        //{ TestLine(), false, "http://f:\u000A/c", null },
        //{ TestLine(), false, "http://f:fifty-two/c", null },
        //{ TestLine(), false, "http://f:999999/c", null },
        //{ TestLine(), false, "http://f: 21 / b ? d # e ", null },
        //{ TestLine(), false, "", null },
        //{ TestLine(), false, "  \u0009", null },
        //{ TestLine(), false, ":foo.com/", null },
        //{ TestLine(), false, ":foo.com\\", null },
        //{ TestLine(), false, ":", null },
        //{ TestLine(), false, ":a", null },
        //{ TestLine(), false, ":/", null },
        //{ TestLine(), false, ":\\", null },
        //{ TestLine(), false, ":#", null },
        //{ TestLine(), false, "#", null },
        //{ TestLine(), false, "#/", null },
        //{ TestLine(), false, "#\\", null },
        //{ TestLine(), false, "#;?", null },
        //{ TestLine(), false, "?", null },
        //{ TestLine(), false, "/", null },
        //{ TestLine(), false, ":23", null },
        //{ TestLine(), false, "/:23", null },
        //{ TestLine(), false, "//", null },
        //{ TestLine(), false, "::", null },
        //{ TestLine(), false, "::23", null },
        //{ TestLine(), false, "foo://", null },
        //{ TestLine(), false, "http://a:b@c:29/d", null },
        //{ TestLine(), false, "http::@c:29", null },
        //{ TestLine(), false, "http://&amp;a:foo(b]c@d:2/", null },
        //{ TestLine(), false, "http://::@c@d:2", null },
        //{ TestLine(), false, "http://foo.com:b@d/", null },
        //{ TestLine(), false, "http://foo.com/\\", null },
        //{ TestLine(), false, "http:\\\\foo.com\\", null },
        //{ TestLine(), false, "http:\\\\a\\b:c\\d @foo.com\\", null },
        //{ TestLine(), false, "foo:/", null },
        //{ TestLine(), false, "foo:/bar.com/", null },
        //{ TestLine(), false, "foo://///////", null },
        //{ TestLine(), false, "foo://///////bar.com/", null },
        //{ TestLine(), false, "foo:////://///", null },
        //{ TestLine(), false, "c:/foo", null },
        //{ TestLine(), false, "    //foo/bar", null },
        //{ TestLine(), false, "http://foo/path;a??e#f#g", null },
        //{ TestLine(), false, "http://foo/abcd?efgh?ijkl", null },
        //{ TestLine(), false, "http://foo/abcd#foo?bar", null },
        //{ TestLine(), false, "[61:24:74]:98", null },
        //{ TestLine(), false, "http://[61:27]:98", null },
        //{ TestLine(), false, "http:[61:27]/:foo", null },
        //{ TestLine(), false, "http://[1::2]:3:4", null },
        //{ TestLine(), false, "http://2001::1", null },
        //{ TestLine(), false, "http://[2001::1", null },
        //{ TestLine(), false, "http://2001::1]", null },
        //{ TestLine(), false, "http://2001::1]:80", null },
        //{ TestLine(), false, "http://[2001::1]", null },
        //{ TestLine(), false, "http://[2001::1]:80", null },
        //{ TestLine(), false, "http://[[::]]", null },
        //{ TestLine(), false, "http://www.google.com/foo?bar=baz#", null },
        //{ TestLine(), false, "http://[www.google.com]/", null },
        //{ TestLine(), false, "http:////////user:@google.com:99?foo", null },
        //{ TestLine(), false, "http://192.0x00A80001", null },
        //{ TestLine(), false, "http://www/foo%2Ehtml", null },
        //{ TestLine(), false, "http://user:pass@/", null },
        //{ TestLine(), false, "http://%25DOMAIN:foobar@foodomain.com/", null },
        //{ TestLine(), false, "http:\\\\www.google.com\\foo", null },
        //{ TestLine(), false, "http://www.google.com/asdf#\\ud800", null },
        //{ TestLine(), false, "http://foo:80/", null },
        //{ TestLine(), false, "http://foo:81/", null },
        //{ TestLine(), false, "httpa://foo:80/", null },
        //{ TestLine(), false, "http://foo:-80/", null },
        //{ TestLine(), false, "https://foo:443/", null },
        //{ TestLine(), false, "https://foo:80/", null },
        //{ TestLine(), false, "ftp://foo:21/", null },
        //{ TestLine(), false, "ftp://foo:80/", null },
        //{ TestLine(), false, "gopher://foo:70/", null },
        //{ TestLine(), false, "gopher://foo:443/", null },
        //{ TestLine(), false, "ws://foo:80/", null },
        //{ TestLine(), false, "ws://foo:81/", null },
        //{ TestLine(), false, "ws://foo:443/", null },
        //{ TestLine(), false, "ws://foo:815/", null },
        //{ TestLine(), false, "wss://foo:80/", null },
        //{ TestLine(), false, "wss://foo:81/", null },
        //{ TestLine(), false, "wss://foo:443/", null },
        //{ TestLine(), false, "wss://foo:815/", null },
        //{ TestLine(), false, "http://example.com/", null },
        //{ TestLine(), false, "http://example.com/", null },
        //{ TestLine(), false, "/", null },
        //{ TestLine(), false, "http://iris.test.ing/re&#x301;sume&#x301;/re&#x301;sume&#x301;.html", null },
        //{ TestLine(), false, "http://iris.test.ing/r&#xE9;sum&#xE9;.html", null },
        //{ TestLine(), false, "http://iris.test.ing/Vi&#xEA;&#x323;tNam.html", null },
        //{ TestLine(), false, "http://iris.test.ing/\uFB01?\uFB01#\uFB01", null },
        //{ TestLine(), false, "http://iris.test.ing/?re&#x301;sume&#x301;#re&#x301;sume&#x301;", null },
        //{ TestLine(), false, "http://iris.test.ing/2\u2075?2\u2075#2\u2075", null },
        //{ TestLine(), false, "http://iris.test.ing/?Vi&#xEA;&#x323;tNam#Vi&#xEA;&#x323;tNam", null },
        //{ TestLine(), false, "http://iris.test.ing/foo?q=\u2665", null },
        //{ TestLine(), false, "http://iris.test.ing/\u1E9B\u0323/?\u1E9B\u0323#\u1E9B\u0323", null },
        //{ TestLine(), false, "http://iris.test.ing/\u212B/?\u212B#\u212B", null },
        //{ TestLine(), false, "http://iris.test.ing/\u1E9B\u0323/?\u1E9B\u0323#\u1E9B\u0323", null },
        //{ TestLine(), false, "http://iris.test.ing/\u1E0B\u0323/?\u1E0B\u0323#\u1E0B\u0323", null },
        //{ TestLine(), false, "http://www.example.com/foo    bar/?   foo   =   bar     #    foohttp://www.example.com/foo    bar/?   foo   =   bar     #    foo", null },
        //{ TestLine(), false, "http://www.example.com/foo%3fbar", null },
        //{ TestLine(), false, "http://www.example.com/foo%2fbar", null },
        //{ TestLine(), false, "%68%74%74%70%3a%2f%2f%77%77%77%2e%65%78%61%6d%70%6c%65%2e%63%6f%6d%2f", null },
        //{ TestLine(), false, "http%3a%2f%2f%77%77%77%2e%65%78%61%6d%70%6c%65%2e%63%6f%6d%2f", null },
        //{ TestLine(), false, "http://%77%77%77%2e%65%78%61%6d%70%6c%65%2e%63%6f%6d%3a%38%30", null },
        //{ TestLine(), false, "http://%A1%C1.com", null },
        //{ TestLine(), false, "http://www.example.com/%A1%C1/?foo=%EF%BD%81", null },
        //{ TestLine(), false, "http://www.example.com/%EF%BD%81/?foo=%A1%C1", null },
        //{ TestLine(), false, "http://www.example.com/ＦＯＯ/?foo=%A1%C1", null },
        //{ TestLine(), false, "http://www.example.com/%A1%C1/?foo=ＦＯＯ", null },
        //{ TestLine(), false, "http://www.example.com/ＦＯＯ/?foo=%A1%C1", null },
        //{ TestLine(), false, "http://www.example.com/D%FCrst", null },
        //{ TestLine(), false, "http://www.example.com/D%C3%BCrst", null },
        //{ TestLine(), false, "http://www.example.com/?D%FCrst", null },
        //{ TestLine(), false, "http://www.example.com/?D%C3%BCrst", null },
        //{ TestLine(), false, "http://user%40example.com", null },
        //{ TestLine(), false, "http://user%3Ainfo%40example.com", null },
        //{ TestLine(), false, "http://user@example.com", null },
        //{ TestLine(), false, "http://user:info@example.com", null },
        //{ TestLine(), false, "http://iris.test.ing/\ufdd0foo", null },
        //{ TestLine(), false, "http://iris.test.ing/\ufdd0foo/bar", null },
        //{ TestLine(), false, "$://iris.test.ing", null },
        //{ TestLine(), false, "a$://iris.test.ing", null },
        //{ TestLine(), false, "http://www.example.com/foo    bar/?   foo   =   bar     #    foo", null },
        //{ TestLine(), false, "", null },
        //{ TestLine(), false, "        htt\u0070://www.example.com/", null },
        //{ TestLine(), false, "      \u0066\u006f\u006fbar\u002ffoo\u003fbar", null },
    };
}