namespace vm2.ExpressionSerialization.JsonTests.ToFromJsonTests;

public partial class ConstantTests
{
    public static readonly TheoryData<string, string, string> ConstantsData = new ()
    {
        { TestLine(), "false",                                                                  "Bool.False.json" },
        { TestLine(), "true",                                                                   "Bool.True.json" },
        { TestLine(), "(byte)5",                                                                "Byte.json" },
        { TestLine(), "'V'",                                                                    "Char.json" },
        { TestLine(), "Math.PI",                                                                "Double.PI.json" },
        { TestLine(), "Math.E",                                                                 "Double.E.json" },
        { TestLine(), "-2.234567891233658E-123",                                                "Double.2.2345.json" },
        { TestLine(), "5.1234567891234567E-123",                                                "Double.5.12345.json" },
        { TestLine(), "-2.234568E-23F",                                                         "Float.2.2345.json" },
        { TestLine(), "5.5123453E-34F",                                                         "Float.5.512345.json" },
        { TestLine(), "5",                                                                      "Int.5.json" },
        { TestLine(), "42",                                                                     "Int.42.json" },
        { TestLine(), "int.Min",                                                                "Int.Min.json" },
        { TestLine(), "int.Max",                                                                "Int.Max.json" },
        { TestLine(), "IntPtr5",                                                                "IntPtr.5.json" },
        { TestLine(), "IntPtr23",                                                               "IntPtr.23.json" },
        { TestLine(), "long0",                                                                  "Long.0.json" },
        { TestLine(), "5L",                                                                     "Long.5.json" },
        { TestLine(), "long.Min",                                                               "Long.Min.json" },
        { TestLine(), "long.Max",                                                               "Long.Max.json" },
        { TestLine(), "long.IntMin",                                                            "Long.IntMin.json" },
        { TestLine(), "long.IntMax",                                                            "Long.IntMax.json" },
        { TestLine(), "long.IntMin-1",                                                          "Long.IntMin-1.json" },
        { TestLine(), "long.IntMax+1",                                                          "Long.IntMax+1.json" },
        { TestLine(), "long.IntMin+1",                                                          "Long.IntMin+1.json" },
        { TestLine(), "long.IntMax-1",                                                          "Long.IntMax-1.json" },
        { TestLine(), "(sbyte)5",                                                               "SignedByte.5.json"},
        { TestLine(), "(sbyte)-5",                                                              "SignedByte.-5.json"},
        { TestLine(), "(short)32000",                                                           "Short.json"},
        { TestLine(), "(uint)5",                                                                "UnsignedInt.5.json"},
        { TestLine(), "(uint)42",                                                               "UnsignedInt.42.json"},
        { TestLine(), "uint.Min",                                                               "UnsignedInt.Min.json"},
        { TestLine(), "uint.Max",                                                               "UnsignedInt.Max.json"},
        { TestLine(), "(UnsignedIntPtr)5",                                                      "UnsignedIntPtr.5.json"},
        { TestLine(), "(UnsignedIntPtr)42",                                                     "UnsignedIntPtr.42.json"},
        { TestLine(), "ulong0",                                                                 "UnsignedLong.0.json"},
        { TestLine(), "(ulong)5",                                                               "UnsignedLong.5.json"},
        { TestLine(), "ulong.Min",                                                              "UnsignedLong.Min.json"},
        { TestLine(), "ulong.Max",                                                              "UnsignedLong.Max.json"},
        { TestLine(), "ulong.IntMax-1",                                                         "UnsignedLong.IntMax-1.json"},
        { TestLine(), "ulong.IntMax",                                                           "UnsignedLong.IntMax.json"},
        { TestLine(), "ulong.IntMax+1",                                                         "UnsignedLong.IntMax+1.json"},
        { TestLine(), "(ushort)5",                                                              "UnsignedShort.5.json"},
        { TestLine(), "(ushort)443",                                                            "UnsignedShort.443.json"},

        { TestLine(), "DateTime(2024, 4, 13, 23, 18, 26, 234, DateTimeKind.Local)",             "DateTime.json" },
        { TestLine(), "DateTimeOffset(2024, 4, 13, 23, 18, 26, 234, new TimeSpan(0, -300, 0))", "DateTimeOffset.json" },
        { TestLine(), "TimeSpan(3, 4, 15, 32, 123)",                                            "TimeSpan.json" },
        { TestLine(), "TimeSpan(-3, 4, 15, 32, 123)",                                           "TimeSpan-.json" },
        { TestLine(), "DBNull.Value",                                                           "DBNull.json" },
        { TestLine(), "5.5M",                                                                   "Decimal.json" },
        { TestLine(), "Guid(\"00112233-4455-6677-8899-aabbccddeeff\")",                         "Guid.json" },
        { TestLine(), "(Half)3.14",                                                             "Half.json" },
        { TestLine(), "abrah-cadabrah",                                                         "String.json" },
        { TestLine(), "Uri(\"http://www.delinea.com\")",                                        "Uri.json" },

        { TestLine(), "EnumFlagsTest.One | EnumFlagsTest.Three",                                "EnumFlags.json" },
        { TestLine(), "EnumTest.Three",                                                         "Enum.json" },

        { TestLine(), "(int?)5",                                                                "NullableInt.json" },
        { TestLine(), "(int?)null",                                                             "NullNullableInt.json" },
        { TestLine(), "(IntField: 1, StringField: \"one\")",                                    "ValueTupleIntString.json" },
        { TestLine(), "(IntPtr)5",                                                              "IntPtr.json" },
        { TestLine(), "(long?)5L",                                                              "NullableLong.json" },
        { TestLine(), "(long?)null",                                                            "NullNullableLong.json" },
        { TestLine(), "(Object1)null",                                                          "Object1Null.json" },
        { TestLine(), "(StructDataContract1)null",                                              "NullNullableStructDataContract1.json" },
        { TestLine(), "(StructSerializable1)null",                                              "NullNullableStructSerializable1.json" },

        { TestLine(), "anonymous",                                                              "Anonymous.json" },
        { TestLine(), "ArraySegment<byte>",                                                     "ByteArraySegment.json" },
        { TestLine(), "ArraySegment<int>([ 1, 2, 3, 4 ], 1, 2)",                                "IntArraySegment.json" },
        { TestLine(), "EnumTest?[]{ EnumTest.One, EnumTest.Two, null, null }",                  "ArrayOfNullableEnums.json" },
        { TestLine(), "BlockingCollection<double>()",                                           "BlockingCollection.json" },
        { TestLine(), "byte[]{ 1, 2, 3, 1, 2, 3, 1, 2, 3, 10 }",                                "ByteArray.json" },
        { TestLine(), "ClassDataContract1()",                                                   "ClassDataContract1.json" },
        { TestLine(), "ClassDataContract1[] { new ClassDataContract1()...",                     "ArrayWithClassDataContract1and2.json" },
        { TestLine(), "ClassDataContract1[] { new(0, \"vm\"), new(1, \"vm2 vm\"), }",           "ArrayOfClassDataContract1.json" },
        { TestLine(), "ClassDataContract2()",                                                   "ClassDataContract2.json" },
        { TestLine(), "ClassSerializable1()",                                                   "ClassSerializable1.json" },
        { TestLine(), "Collection<int>([1, 2, 3, 4])",                                          "IntCollection.json" },
        { TestLine(), "ConcurrentBag<int>([1, 2, 3, 4])",                                       "IntConcurrentBag.json" },
        { TestLine(), "ConcurrentDictionary<int, string>{ [1] = \"one\", [2]=\"two\" }",        "ConcurrentDictionaryIntString.json" },
        { TestLine(), "ConcurrentQueue<int>([1, 2, 3, 4])",                                     "IntConcurrentQueue.json" },
        { TestLine(), "ConcurrentStack<int>([1, 2, 3, 4])",                                     "IntConcurrentStack.json" },
        { TestLine(), "Dictionary<int, string>{ [1] =\"one\", [2]=\"two\" }",                   "DictionaryIntString.json" },
        { TestLine(), "Dictionary<int, string>{ [1] =\"one\", [2]=\"two\" }",                   "DictionaryIntString.json" },
        { TestLine(), "Frozen byte[]{ 1, 2, 3, 1, 2, 3, 1, 2, 3, 10 }",                         "ByteArrayFrozen.json" },
        { TestLine(), "Frozen decimal[]{ 1, 2, 3, 4 }",                                         "DecimalFrozenSet.json" },
        { TestLine(), "Frozen Dictionary<int, string?>{ [1] = \"one\", [2] = \"two\"...",       "IntNullableStringDictionary.json" },
        { TestLine(), "Frozen Dictionary<int, string>{ [1] = \"one\", [2] = \"two\", [3]...}",  "IntStringDictionaryFrozen.json" },
        { TestLine(), "Frozen Dictionary<int, string>{ [1] =\"one\", [2]=\"two\" }",            "FrozenDictionaryIntString.json" },
        { TestLine(), "Frozen EnumTest?[]{ EnumTest.One, EnumTest.Two, null, null }",           "ArrayOfNullableEnumsFrozen.json" },
        { TestLine(), "Frozen int?[]{ 1, 2, null, null }",                                      "ArrayOfNullableIntFrozen.json" },
        { TestLine(), "Frozen int[]{ 1, 2, 3, 4 }",                                             "ArrayOfIntFrozen.json" },
        { TestLine(), "Frozen object[anonymous]",                                               "AnonymousFrozenArray.json" },
        { TestLine(), "HashSet<int>([1, 2, 3, 4])",                                             "IntHashSet.json" },
        { TestLine(), "Hashtable(new Dictionary<int, string>{ [1] =\"one\", [2]=\"two\" })",    "Dictionary.json" },
        { TestLine(), "ImmutableArray.Create(1, 2, 3, 4 )",                                     "IntImmutableArray.json" },
        { TestLine(), "ImmutableDictionary.Create<int,string>().Add(1, \"one\").Add(2, \"two\")", "ImmutableDictionaryIntString.json" },
        { TestLine(), "ImmutableHashSet.Create(1, 2, 3, 4 )",                                   "IntImmutableHashSet.json" },
        { TestLine(), "ImmutableList.Create(1, 2, 3, 4 )",                                      "IntImmutableList.json" },
        { TestLine(), "ImmutableQueue.Create(1, 2, 3, 4 )",                                     "IntImmutableQueue.json" },
        { TestLine(), "ImmutableSortedDictionary.Create<int,string>().Add(1, \"one\").Add(2, \"two\")", "ImmutableSortedDictionaryIntString.json" },
        { TestLine(), "ImmutableSortedSet.Create(1, 2, 3, 4 )",                                 "IntImmutableSortedSet.json" },
        { TestLine(), "ImmutableStack.Create(1, 2, 3, 4 )",                                     "IntImmutableStack.json" },
        { TestLine(), "int?[]{ 1, 2, null, null }",                                             "ArrayOfNullableInt.json" },
        { TestLine(), "int[]{ 1, 2, 3, 4 }",                                                    "ArrayOfInt.json" },
        { TestLine(), "LinkedList<int>([1, 2, 3, 4])",                                          "IntLinkedList.json" },
        { TestLine(), "List<int?>{ 1, 2, null, null }",                                         "ListOfNullableInt.json" },
        { TestLine(), "List<int>([1, 2, 3, 4])",                                                "IntList.json" },
        { TestLine(), "Memory<byte>([1, 2, 3, 1, 2, 3, 1, 2, 3, 10 ])",                         "ByteMemory.json" },
        { TestLine(), "Memory<int>([ 1, 2, 3, 4 ])",                                            "IntMemory.json" },
        { TestLine(), "null",                                                                   "NullObject.json" },
        { TestLine(), "object()",                                                               "Object.json" },
        { TestLine(), "Object1()",                                                              "Object1.json" },
        { TestLine(), "Queue<int>([ 1, 2, 3, 4 ])",                                             "IntQueue.json" },
        { TestLine(), "Queue<int>([1, 2, 3, 4])",                                               "IntQueue.json" },
        { TestLine(), "ReadOnlyCollection<int>([1, 2, 3, 4])",                                  "IntReadOnlyCollection.json" },
        { TestLine(), "ReadOnlyDictionary<int, string>...",                                     "ReadOnlyDictionaryIntString.json" },
        { TestLine(), "ReadOnlyMemory<byte>([1, 2, 3, 1, 2, 3, 1, 2, 3, 10 ])",                 "ByteReadOnlyMemory.json" },
        { TestLine(), "ReadOnlyMemory<int>([ 1, 2, 3, 4 ])",                                    "IntReadOnlyMemory.json" },
        { TestLine(), "SortedDictionary<int, string>{ [1] =\"one\", [2]=\"two\" }",             "SortedDictionaryIntString.json" },
        { TestLine(), "SortedSet<int>([1, 2, 3, 4])",                                           "IntSortedSet.json" },
        { TestLine(), "Stack<int>([ 1, 2, 3, 4 ])",                                             "IntStack.json" },
        { TestLine(), "Stack<int>([1, 2, 3, 4])",                                               "IntStack.json" },
        { TestLine(), "StructDataContract1() { IntProperty = 7, StringProperty = \"vm\" }",     "StructDataContract1-2.json" },
        { TestLine(), "StructDataContract1()",                                                  "StructDataContract1.json" },
        { TestLine(), "StructDataContract1?() { IntProperty = 7, StringProperty = \"vm\" }",    "NullableStructDataContract1.json" },
        { TestLine(), "StructDataContract1?[]",                                                 "ArrayOfNullableStructDataContract1.json" },
        { TestLine(), "StructDataContract1[]",                                                  "ArrayOfStructDataContract1.json" },
        { TestLine(), "StructSerializable1() { IntProperty = 7, StringProperty = \"vm\" }",     "NullableStructSerializable1.json" },
        { TestLine(), "StructSerializable1()",                                                  "StructSerializable1.json" },
        { TestLine(), "StructSerializable1?[]",                                                 "ArrayOfNullableStructSerializable1.json" },
        { TestLine(), "StructSerializable1[]",                                                  "ArrayOfStructSerializable1.json" },
        { TestLine(), "Tuple<int, string>(1, \"one\")",                                         "ClassTupleIntString.json" },
    };
}
