namespace vm2.XmlExpressionSerialization.Abstractions;

/// <summary>
/// Interface IDocumentTransform represents a transform of a some document model (generated by IExpressionTransform)
/// node to a LINQ expression.
/// (The document could be loaded from some stream.)
/// </summary>
/// <typeparam name="TNode">The type of the top level document model node.</typeparam>
public interface IDocumentTransform<in TNode>
{
    /// <summary>
    /// Transform the specified document model node of type `TNode` to a LINQ expression.
    /// </summary>
    /// <param name="node">The document node to be transformed.</param>
    /// <returns>The resultant expression.</returns>
    Expression Transform(TNode node);
}
