namespace vm2.ExpressionSerialization.Xml;

interface IConstantXmlTransform
{
    /// <summary>
    /// Transforms the specified constant.
    /// </summary>
    /// <param name="constant">The constant to be transformed.</param>
    /// <param name="type">The type of the constant (if needed).</param>
    /// <returns>The XElement generated by the serializer representing the type and the value of the <paramref name="constant"/>.</returns>
    XElement Transform(object constant, Type type);

    /// <summary>
    /// Transforms an object from the specified XML element.
    /// </summary>
    /// <param name="element">The XML element to deserialize from.</param>
    /// <param name="type">The type of the constant (if needed).</param>
    /// <returns>The deserialized object.</returns>
    object Transform(XElement element, Type type);
}