namespace ExpressionSerializationTests;

public partial class TransformOptionsTests
{
    public static TheoryData<string, string, string, Identifiers, bool> TransformIdentifiersData => new() {
        { TestLine(), "",                         "",                 Identifiers.Camel, true  },
        { TestLine(), " ",                        "",                 Identifiers.Camel, true  },
        { TestLine(), " Abc",                     "",                 Identifiers.Camel, true  },
        { TestLine(), "1BC",                      "",                 Identifiers.Camel, true  },
        { TestLine(), "@__camel__Case__ ",        "",                 Identifiers.Camel, true  },
        { TestLine(), "a",                        "a",                Identifiers.Camel, false },
        { TestLine(), "A",                        "a",                Identifiers.Camel, false },
        { TestLine(), "ABC",                      "aBC",              Identifiers.Camel, false },
        { TestLine(), "CamelCase",                "camelCase",        Identifiers.Camel, false },
        { TestLine(), "camelCase",                "camelCase",        Identifiers.Camel, false },
        { TestLine(), "@enum",                    "enum",             Identifiers.Camel, false },
        { TestLine(), "_CamelCase",               "camelCase",        Identifiers.Camel, false },
        { TestLine(), "__Camel_Case",             "camelCase",        Identifiers.Camel, false },
        { TestLine(), "__camel_case",             "camelCase",        Identifiers.Camel, false },
        { TestLine(), "@__camel_case",            "camelCase",        Identifiers.Camel, false },
        { TestLine(), "@__camel_case__",          "camelCase",        Identifiers.Camel, false },
        { TestLine(), "@__8camel_case__",         "8camelCase",       Identifiers.Camel, false },
        { TestLine(), "@__camel_7case__",         "camel7case",       Identifiers.Camel, false },
        { TestLine(), "@__camel_a_case__",        "camelACase",       Identifiers.Camel, false },
        { TestLine(), "@__camel_with_5_cases__",  "camelWith5Cases",  Identifiers.Camel, false },

        { TestLine(), "",                         "",                 Identifiers.Pascal, true  },
        { TestLine(), " ",                        "",                 Identifiers.Pascal, true  },
        { TestLine(), " Abc",                     "",                 Identifiers.Pascal, true  },
        { TestLine(), "1BC",                      "",                 Identifiers.Pascal, true  },
        { TestLine(), "@__camel__Case__ ",        "",                 Identifiers.Pascal, true  },
        { TestLine(), "a",                        "A",                Identifiers.Pascal, false },
        { TestLine(), "A",                        "A",                Identifiers.Pascal, false },
        { TestLine(), "ABC",                      "ABC",              Identifiers.Pascal, false },
        { TestLine(), "CamelCase",                "CamelCase",        Identifiers.Pascal, false },
        { TestLine(), "camelCase",                "CamelCase",        Identifiers.Pascal, false },
        { TestLine(), "@enum",                    "Enum",             Identifiers.Pascal, false },
        { TestLine(), "_CamelCase",               "CamelCase",        Identifiers.Pascal, false },
        { TestLine(), "__Camel_Case",             "CamelCase",        Identifiers.Pascal, false },
        { TestLine(), "__camel_case",             "CamelCase",        Identifiers.Pascal, false },
        { TestLine(), "@__camel_case",            "CamelCase",        Identifiers.Pascal, false },
        { TestLine(), "@__camel_case__",          "CamelCase",        Identifiers.Pascal, false },
        { TestLine(), "@__8camel_case__",         "8camelCase",       Identifiers.Pascal, false },
        { TestLine(), "@__camel_7case__",         "Camel7case",       Identifiers.Pascal, false },
        { TestLine(), "@__camel_a_case__",        "CamelACase",       Identifiers.Pascal, false },
        { TestLine(), "@__camel_with_5_cases__",  "CamelWith5Cases",  Identifiers.Pascal, false },

        { TestLine(), "",                         "",                    Identifiers.SnakeLower, true  },
        { TestLine(), " ",                        "",                    Identifiers.SnakeLower, true  },
        { TestLine(), " Abc",                     "",                    Identifiers.SnakeLower, true  },
        { TestLine(), "1BC",                      "",                    Identifiers.SnakeLower, true  },
        { TestLine(), "@__camel__Case__ ",        "",                    Identifiers.SnakeLower, true  },
        { TestLine(), "a",                        "a",                   Identifiers.SnakeLower, false },
        { TestLine(), "A",                        "a",                   Identifiers.SnakeLower, false },
        { TestLine(), "ABC",                      "a_b_c",               Identifiers.SnakeLower, false },
        { TestLine(), "CamelCase",                "camel_case",          Identifiers.SnakeLower, false },
        { TestLine(), "camelCase",                "camel_case",          Identifiers.SnakeLower, false },
        { TestLine(), "@enum",                    "enum",                Identifiers.SnakeLower, false },
        { TestLine(), "_CamelCase",               "camel_case",          Identifiers.SnakeLower, false },
        { TestLine(), "__Camel_Case",             "camel_case",          Identifiers.SnakeLower, false },
        { TestLine(), "__camel_case",             "camel_case",          Identifiers.SnakeLower, false },
        { TestLine(), "@__camel_case",            "camel_case",          Identifiers.SnakeLower, false },
        { TestLine(), "@__camel_case__",          "camel_case",          Identifiers.SnakeLower, false },
        { TestLine(), "@__8camel_case__",         "8camel_case",         Identifiers.SnakeLower, false },
        { TestLine(), "@__camel_7case__",         "camel_7case",         Identifiers.SnakeLower, false },
        { TestLine(), "@__camel_a_case__",        "camel_a_case",        Identifiers.SnakeLower, false },
        { TestLine(), "@__camel_with_5_cases__",  "camel_with_5_cases",  Identifiers.SnakeLower, false },

        { TestLine(), "",                         "",                    Identifiers.SnakeUpper, true  },
        { TestLine(), " ",                        "",                    Identifiers.SnakeUpper, true  },
        { TestLine(), " Abc",                     "",                    Identifiers.SnakeUpper, true  },
        { TestLine(), "1BC",                      "",                    Identifiers.SnakeUpper, true  },
        { TestLine(), "@__camel__Case__ ",        "",                    Identifiers.SnakeUpper, true  },
        { TestLine(), "a",                        "A",                   Identifiers.SnakeUpper, false },
        { TestLine(), "A",                        "A",                   Identifiers.SnakeUpper, false },
        { TestLine(), "ABC",                      "A_B_C",               Identifiers.SnakeUpper, false },
        { TestLine(), "CamelCase",                "CAMEL_CASE",          Identifiers.SnakeUpper, false },
        { TestLine(), "camelCase",                "CAMEL_CASE",          Identifiers.SnakeUpper, false },
        { TestLine(), "@enum",                    "ENUM",                Identifiers.SnakeUpper, false },
        { TestLine(), "_CamelCase",               "CAMEL_CASE",          Identifiers.SnakeUpper, false },
        { TestLine(), "__Camel_Case",             "CAMEL_CASE",          Identifiers.SnakeUpper, false },
        { TestLine(), "__camel_case",             "CAMEL_CASE",          Identifiers.SnakeUpper, false },
        { TestLine(), "@__camel_case",            "CAMEL_CASE",          Identifiers.SnakeUpper, false },
        { TestLine(), "@__camel_case__",          "CAMEL_CASE",          Identifiers.SnakeUpper, false },
        { TestLine(), "@__8camel_case__",         "8CAMEL_CASE",         Identifiers.SnakeUpper, false },
        { TestLine(), "@__camel_7case__",         "CAMEL_7CASE",         Identifiers.SnakeUpper, false },
        { TestLine(), "@__camel_a_case__",        "CAMEL_A_CASE",        Identifiers.SnakeUpper, false },
        { TestLine(), "@__camel_with_5_cases__",  "CAMEL_WITH_5_CASES",  Identifiers.SnakeUpper, false },

        { TestLine(), "",                         "",                    Identifiers.KebabLower, true  },
        { TestLine(), " ",                        "",                    Identifiers.KebabLower, true  },
        { TestLine(), " Abc",                     "",                    Identifiers.KebabLower, true  },
        { TestLine(), "1BC",                      "",                    Identifiers.KebabLower, true  },
        { TestLine(), "@__camel__Case__ ",        "",                    Identifiers.KebabLower, true  },
        { TestLine(), "a",                        "a",                   Identifiers.KebabLower, false },
        { TestLine(), "A",                        "a",                   Identifiers.KebabLower, false },
        { TestLine(), "ABC",                      "a-b-c",               Identifiers.KebabLower, false },
        { TestLine(), "CamelCase",                "camel-case",          Identifiers.KebabLower, false },
        { TestLine(), "camelCase",                "camel-case",          Identifiers.KebabLower, false },
        { TestLine(), "@enum",                    "enum",                Identifiers.KebabLower, false },
        { TestLine(), "_CamelCase",               "camel-case",          Identifiers.KebabLower, false },
        { TestLine(), "__Camel_Case",             "camel-case",          Identifiers.KebabLower, false },
        { TestLine(), "__camel_case",             "camel-case",          Identifiers.KebabLower, false },
        { TestLine(), "@__camel_case",            "camel-case",          Identifiers.KebabLower, false },
        { TestLine(), "@__camel_case__",          "camel-case",          Identifiers.KebabLower, false },
        { TestLine(), "@__8camel_case__",         "8camel-case",         Identifiers.KebabLower, false },
        { TestLine(), "@__camel_7case__",         "camel-7case",         Identifiers.KebabLower, false },
        { TestLine(), "@__camel_a_case__",        "camel-a-case",        Identifiers.KebabLower, false },
        { TestLine(), "@__camel_with_5_cases__",  "camel-with-5-cases",  Identifiers.KebabLower, false },

        { TestLine(), "",                         "",                    Identifiers.KebabUpper, true  },
        { TestLine(), " ",                        "",                    Identifiers.KebabUpper, true  },
        { TestLine(), " Abc",                     "",                    Identifiers.KebabUpper, true  },
        { TestLine(), "1BC",                      "",                    Identifiers.KebabUpper, true  },
        { TestLine(), "@__camel__Case__ ",        "",                    Identifiers.KebabUpper, true  },
        { TestLine(), "a",                        "A",                   Identifiers.KebabUpper, false },
        { TestLine(), "A",                        "A",                   Identifiers.KebabUpper, false },
        { TestLine(), "ABC",                      "A-B-C",               Identifiers.KebabUpper, false },
        { TestLine(), "CamelCase",                "CAMEL-CASE",          Identifiers.KebabUpper, false },
        { TestLine(), "camelCase",                "CAMEL-CASE",          Identifiers.KebabUpper, false },
        { TestLine(), "@enum",                    "ENUM",                Identifiers.KebabUpper, false },
        { TestLine(), "_CamelCase",               "CAMEL-CASE",          Identifiers.KebabUpper, false },
        { TestLine(), "__Camel_Case",             "CAMEL-CASE",          Identifiers.KebabUpper, false },
        { TestLine(), "__camel_case",             "CAMEL-CASE",          Identifiers.KebabUpper, false },
        { TestLine(), "@__camel_case",            "CAMEL-CASE",          Identifiers.KebabUpper, false },
        { TestLine(), "@__camel_case__",          "CAMEL-CASE",          Identifiers.KebabUpper, false },
        { TestLine(), "@__8camel_case__",         "8CAMEL-CASE",         Identifiers.KebabUpper, false },
        { TestLine(), "@__camel_7case__",         "CAMEL-7CASE",         Identifiers.KebabUpper, false },
        { TestLine(), "@__camel_a_case__",        "CAMEL-A-CASE",        Identifiers.KebabUpper, false },
        { TestLine(), "@__camel_with_5_cases__",  "CAMEL-WITH-5-CASES",  Identifiers.KebabUpper, false },
    };

    public static TheoryData<string, Type, string, TypeNames, bool> TransformTypeNamesData => new() {
        { TestLine(), typeof(Uri), "System.Uri, System.Private.Uri, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", TypeNames.AssemblyQualifiedName, false},
        { TestLine(), typeof(Uri), "System.Uri", TypeNames.FullName, false},
        { TestLine(), typeof(Uri), "Uri", TypeNames.Name, false},
    };

    public static TheoryData<string, string, TypeNames, bool> TransformTypeNamesLocalData => new() {
        { TestLine(), "<>f__AnonymousType0`2[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ExpressionSerializationTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=33dd0fdd47b5922b", TypeNames.AssemblyQualifiedName, false},
        { TestLine(), "<>f__AnonymousType0`2[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]", TypeNames.FullName, false},
        { TestLine(), "<>f__AnonymousType0`2", TypeNames.Name, false},
    };
}
