namespace vm2.RegexLibTests;

public class WindowsPathnameTests(
    RegexLibTestsFixture fixture,
    ITestOutputHelper output) : RegexTests(fixture, output)
{
    static readonly string boarderLengthName = new('a', 260);
    static readonly string overBoardLengthName = new('a', 261);

    public static TheoryData<string, bool, string, Captures?> WinFilenameData => new() {
        { TestFileLine(), false, "", null },
        { TestFileLine(), false, " ", null },
        { TestFileLine(), false, ".", null },
        { TestFileLine(), false, "..", null },
        { TestFileLine(), false, "con", null },
        { TestFileLine(), false, "con.txt", null },
        { TestFileLine(), false, "lpt1", null },
        { TestFileLine(), false, "lpt1.txt", null },
        { TestFileLine(), true,  "a", null },
        { TestFileLine(), true,  "C", null },
        { TestFileLine(), true,  "ж", null },
        { TestFileLine(), true,  "Ж", null },
        { TestFileLine(), true,  "ab", null },
        { TestFileLine(), true,  "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm", null },
        { TestFileLine(), true,  "QWERTYUIOPASDFGHJKLZXCVBNM qwertyuiopasdfghjklzxcvbnm", null },
        { TestFileLine(), true,  "QWERTYUIOPASDFGHJKLZXCVBNM.qwertyuiopasdfghjklzxcvbnm", null },
        { TestFileLine(), false, "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm.", null },
        { TestFileLine(), false, "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm ", null },
        { TestFileLine(), true,  boarderLengthName, null },
        { TestFileLine(), false, overBoardLengthName, null },
        { TestFileLine(), true,  "явертъуиопасдфгхйклзьцжбнмшщюч ЯВЕРТЪУИОПАСДФГХЙКЛЗЬЦЖБНМШЩЮЧ", null },
        // Edge and additional tests
        { TestFileLine("File name with dash and underscore"), true, "foo-bar_baz", null },
        { TestFileLine("File name with space"), true, "file name.txt", null },
        { TestFileLine("File name with Unicode"), true, "файл.txt", null },
        { TestFileLine("File name with leading dot"), true, ".hidden", null },
        { TestFileLine("File name with multiple dots"), true, "archive.tar.gz", null },
        { TestFileLine("File name with trailing dot (should not match)"), false, "file.", null },
        { TestFileLine("File name with trailing space (should not match)"), false, "file ", null },
        { TestFileLine("File name with reserved character < (should not match)"), false, "file<name", null },
        { TestFileLine("File name with reserved character > (should not match)"), false, "file>name", null },
        { TestFileLine("File name with reserved character : (should not match)"), false, "file:name", null },
        { TestFileLine("File name with reserved character \" (should not match)"), false, "file\"name", null },
        { TestFileLine("File name with reserved character / (should not match)"), false, "file/name", null },
        { TestFileLine("File name with reserved character \\ (should not match)"), false, "file\\name", null },
        { TestFileLine("File name with reserved character | (should not match)"), false, "file|name", null },
        { TestFileLine("File name with reserved character ? (should not match)"), false, "file?name", null },
        { TestFileLine("File name with reserved character * (should not match)"), false, "file*name", null },
        { TestFileLine("File name with null character (should not match)"), false, "abc\0def", null },
        { TestFileLine("File name with only slashes (should not match)"), false, "////", null },
        { TestFileLine("File name with only spaces (should not match)"), false, "   ", null },
        { TestFileLine("File name with only underscores"), true, "____", null },
        { TestFileLine("File name with only dashes"), true, "----", null },
        { TestFileLine("File name with only numbers"), true, "1234567890", null },
        { TestFileLine("File name with max length 260"), true, boarderLengthName, null },
        { TestFileLine("File name with length 261 (should not match)"), false, overBoardLengthName, null },
    };

    [Theory]
    [MemberData(nameof(WinFilenameData))]
    public void TestWinFilename(string TestLine, bool shouldBe, string fileName, Captures? captures)
        => base.RegexTest(WindowsPathname.DiskFilename(), TestLine, shouldBe, fileName, captures);

    public static TheoryData<string, bool, string, Captures?> WinPathnameData => new() {
        { TestFileLine(), false, "", null },
        { TestFileLine(), false, " ", null },
        { TestFileLine(), false, ".", null },
        { TestFileLine(), false, "..", null },
        { TestFileLine(), false, "con", null },
        { TestFileLine(), false, "con.txt", null },
        { TestFileLine(), false, "lpt1", null },
        { TestFileLine(), false, "lpt1.txt", null },
        { TestFileLine(), false, "a.", null },
        { TestFileLine(), false, "a ", null },
        { TestFileLine(), true, "a", new() { ["drive"] = "", ["path"] = "", ["file"] = "a" } },
        { TestFileLine(), true, "C", new() { ["drive"] = "", ["path"] = "", ["file"] = "C" } },
        { TestFileLine(), true, "ж", new() { ["drive"] = "", ["path"] = "", ["file"] = "ж" } },
        { TestFileLine(), true, "Ж", new() { ["drive"] = "", ["path"] = "", ["file"] = "Ж" } },
        { TestFileLine(), true, "ab", new() { ["drive"] = "", ["path"] = "", ["file"] = "ab" } },
        { TestFileLine(), true, "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm", new() { ["drive"] = "", ["path"] = "", ["file"] = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm" } },
        { TestFileLine(), true, "QWERTYUIOPASDFGHJKLZXCVBNM qwertyuiopasdfghjklzxcvbnm", new() { ["drive"] = "", ["path"] = "", ["file"] = "QWERTYUIOPASDFGHJKLZXCVBNM qwertyuiopasdfghjklzxcvbnm" } },
        { TestFileLine(), true, "QWERTYUIOPASDFGHJKLZXCVBNM.qwertyuiopasdfghjklzxcvbnm", new() { ["drive"] = "", ["path"] = "", ["file"] = "QWERTYUIOPASDFGHJKLZXCVBNM.qwertyuiopasdfghjklzxcvbnm" } },
        { TestFileLine(), false, "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm.", null },
        { TestFileLine(), false, "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm ", null },
        { TestFileLine(), true, boarderLengthName, new() { ["drive"] = "", ["path"] = "", ["file"] = boarderLengthName } },
        { TestFileLine(), false, overBoardLengthName, null },
        { TestFileLine(), true, "явертъуиопасдфгхйклзьцжбнмшщюч ЯВЕРТЪУИОПАСДФГХЙКЛЗЬЦЖБНМШЩЮЧ", new() { ["drive"] = "", ["path"] = "", ["file"] = "явертъуиопасдфгхйклзьцжбнмшщюч ЯВЕРТЪУИОПАСДФГХЙКЛЗЬЦЖБНМШЩЮЧ" } },
        { TestFileLine(), false, @"a:com1", null },
        { TestFileLine(), false, @"ъ:a", null },
        { TestFileLine(), false, @"a:"+boarderLengthName, new() { ["drive"] = "a", ["path"] = "", ["file"] = boarderLengthName } },
        { TestFileLine(), false, @"a:a.", null },
        { TestFileLine(), false, @"a:a ", null },
        { TestFileLine(), true, @"a:a", new() { ["drive"] = "a", ["path"] = "", ["file"] = "a" } },
        { TestFileLine(), true, @"B:a", new() { ["drive"] = "B", ["path"] = "", ["file"] = "a" } },
        { TestFileLine(), false, @"a:/com2", null },
        { TestFileLine(), false, @"a:/com2.bin", null },
        { TestFileLine(), false, @"a:", null },
        { TestFileLine(), true, @"a:/a", new() { ["drive"] = "a", ["path"] = @"/", ["file"] = "a" } },
        { TestFileLine(), true, @"a:\a", new() { ["drive"] = "a", ["path"] = @"\", ["file"] = "a" } },
        { TestFileLine(), true, @"a:b/a", new() { ["drive"] = "a", ["path"] = "b", ["file"] = "a" } },
        { TestFileLine(), true, @"a:./a", new() { ["drive"] = "a", ["path"] = ".", ["file"] = "a" } },
        { TestFileLine(), true, @"a:../a", new() { ["drive"] = "a", ["path"] = "..", ["file"] = "a" } },
        { TestFileLine(), false, @"a:lpt2/a", null },
        { TestFileLine(), false, @"a:lpt2.txt/a", null },
        { TestFileLine(), false, @"a:/b/lpt2/a", null },
        { TestFileLine(), false, @"a:/b/lpt2.txt/a", null },
        { TestFileLine(), false, @"a:/b/c/d/lpt2", null },
        { TestFileLine(), false, @"a:/b/c/d/lpt2.txt", null },
        { TestFileLine(), false, @"a:/b/c./d/lp", null },
        { TestFileLine(), false, @"a:/b/c./d/lp.txt", null },
        { TestFileLine(), false, @"a:/b/c /d/lp", null },
        { TestFileLine(), false, @"a:/b/c /d/lp.txt", null },
        { TestFileLine(), true, @"a:b\a", new() { ["drive"] = "a", ["path"] = @"b", ["file"] = "a" } },
        { TestFileLine(), true, @"a:/bb/a", new() { ["drive"] = "a", ["path"] = @"/bb", ["file"] = "a" } },
        { TestFileLine(), true, @"a:/bb/cc/aa.aa", new() { ["drive"] = "a", ["path"] = @"/bb/cc", ["file"] = "aa.aa" } },
        { TestFileLine(), true, @"a:bb/cc/aa.aa", new() { ["drive"] = "a", ["path"] = @"bb/cc", ["file"] = "aa.aa" } },
        { TestFileLine(), true, @"bb/cc/aa.aa", new() { ["drive"] = "", ["path"] = @"bb/cc", ["file"] = "aa.aa" } },
        { TestFileLine(), true, @"a:/./a", new() { ["drive"] = "a", ["path"] = @"/.", ["file"] = "a" } },
        { TestFileLine(), true, @"a:../../a", new() { ["drive"] = "a", ["path"] = @"../..", ["file"] = "a" } },
        { TestFileLine(), true, @"a:..\../a", new() { ["drive"] = "a", ["path"] = @"..\..", ["file"] = "a" } },
        { TestFileLine(), true, @"a:\./a", new() { ["drive"] = "a", ["path"] = @"\.", ["file"] = "a" } },
        { TestFileLine(), true, @"a:\bb\a", new() { ["drive"] = "a", ["path"] = @"\bb", ["file"] = "a" } },
        { TestFileLine(), true, @"b\a", new() { ["drive"] = "", ["path"] = @"b", ["file"] = "a" } },
        { TestFileLine(), true, @"/bb/a", new() { ["drive"] = "", ["path"] = @"/bb", ["file"] = "a" } },
        { TestFileLine(), true, @"/bb/cc/aa.aa", new() { ["drive"] = "", ["path"] = @"/bb/cc", ["file"] = "aa.aa" } },
        { TestFileLine(), true, @"/./a", new() { ["drive"] = "", ["path"] = @"/.", ["file"] = "a" } },
        { TestFileLine(), true, @"../../a", new() { ["drive"] = "", ["path"] = @"../..", ["file"] = "a" } },
        { TestFileLine(), true, @"..\../a", new() { ["drive"] = "", ["path"] = @"..\..", ["file"] = "a" } },
        { TestFileLine(), true, @"\./a", new() { ["drive"] = "", ["path"] = @"\.", ["file"] = "a" } },
        { TestFileLine(), true, @"\bb\a", new() { ["drive"] = "", ["path"] = @"\bb", ["file"] = "a" } },
        { TestFileLine(), false, $@"a:\{boarderLengthName}\a", null },
        { TestFileLine(), false, $@"\{boarderLengthName}", null },
        { TestFileLine(), false, $@"a:\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\012345678901234567890123456789012345678901.txt",
                                null  },

        { TestFileLine(), true,  $@"a:\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\01234567890123456789012345678901234567890.txt",
                             new()
                             {
                                ["drive"] = "a",
                                ["path"] = @"\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm",
                                ["file"] = "01234567890123456789012345678901234567890.txt" }
                             },
        { TestFileLine("UNC path - should not match (not supported yet)"), false, @"\\server\share\file.txt", null },
        { TestFileLine("Device name in subdirectory - should match"), false, @"a:\folder\con\file.txt", null },
        { TestFileLine("Path with null character (should not match)"), false, "abc\0def", null },
        { TestFileLine("Path with only slashes (should not match)"), false, @"\\\\", null },
        { TestFileLine("Path with mixed separators"), true, @"a:/folder\sub/file.txt", new() { ["drive"] = "a", ["path"] = @"/folder\sub", ["file"] = "file.txt" } },
        { TestFileLine("Path with only dots (should match as file)"), false, ".", null },
        { TestFileLine("Path with only double dots (should match as file)"), false, "..", null },
        { TestFileLine("Path with trailing backslash (should not match)"), false, @"C:\abc\", null },
        { TestFileLine("Path with multiple consecutive separators (should not match)"), false, @"a:\\b\\c\\file.txt", null },
        { TestFileLine("Path with space in file name"), true, @"a:\folder\file name.txt", new() { ["drive"] = "a", ["path"] = @"\folder", ["file"] = "file name.txt" } },
        { TestFileLine("Path with dash and underscore"), true, @"a:\foo-bar_baz.txt", new()
        {
            ["drive"] = "a",
            ["path"] = @"\",
            ["file"] = "foo-bar_baz.txt",
        } },
        { TestFileLine("Path with leading backslash and dot file"), true, @"\folder\.hidden", new() { ["drive"] = "", ["path"] = @"\folder", ["file"] = ".hidden" } },
        { TestFileLine("Path with Unicode characters"), true, @"a:\папка\файл.txt", new() { ["drive"] = "a", ["path"] = @"\папка", ["file"] = "файл.txt" } },
    };

    [Theory]
    [MemberData(nameof(WinPathnameData))]
    public void TestWinPathname(string TestLine, bool shouldBe, string pathname, Captures? captures)
        => base.RegexTest(WindowsPathname.Pathname(), TestLine, shouldBe, pathname, captures);
}
