global using System;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.Frozen;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.Serialization;
global using System.Text;
global using System.Text.Encodings.Web;
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Xml;
global using System.Xml.Linq;
global using System.Xml.Schema;

global using vm2.ExpressionSerialization.Abstractions;
global using vm2.ExpressionSerialization.Conventions;
global using vm2.ExpressionSerialization.Exceptions;
global using vm2.ExpressionSerialization.Extensions;

global using static vm2.ExpressionSerialization.Extensions.DebugExtensions;